name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Zip Lambda Function
      run: |
        cd lambda
        zip function.zip lambda_function.py

    - name: Deploy Lambda
      run: |
        aws lambda update-function-code \
          --function-name my-serverless-app \
          --zip-file fileb://lambda/function.zip
